version: '3.4'

networks:
  todo-app:

services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    platform: linux/amd64
    environment:
      - POSTGRES_DB=webApi
      - POSTGRES_USER=sa
      - POSTGRES_PASSWORD=Root1234
    ports:
      - "5433:5432"  # Cambiado el puerto del host a 5433
    networks:
      - todo-app
    volumes:
      - postgresql-container-data:/var/lib/postgresql/data

  todo-app-api:
    container_name: todo-app-api
    image: ${DOCKER_REGISTRY-}todo-app-api
    ports:
      - "80:80"
    build:
      context: .
      dockerfile: TodoApp/Dockerfile
    depends_on:
      - postgresql
    networks:
      - todo-app
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=postgresql;Database=webApi;Username=sa;Password=Root1234;TrustServerCertificate=True

volumes:
  postgresql-container-data:
